services:
  postgres_driven-ops_database:
    image: postgres
    container_name: postgres_driven-ops_database
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env
    volumes:
      - pg_driven-ops_database:/var/lib/postgresql/data

  node_driven-ops_app:
    container_name: node_driven-ops_app
    build: ./back-end
    ports:
      - 5000:5000
    env_file:
      - back-end/.env

  react_driven-ops_app:
    container_name: react_driven-ops_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html

  nginx_driven-ops_app:
    container_name: nginx_driven-ops_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_driven-ops_database
      - node_driven-ops_app
      - react_driven-ops_app

volumes:
  pg_driven-ops_database:
  build_react:
