on:
  push:
    branches:
      - main
name: Build and Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: ${{secrets.PG_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.PG_PW}}
          envkey_POSTGRES_DB: ${{secrets.PG_DB}}
          envkey_DATABASE_URL: ${{secrets.DB_URL}}
          directory: back-end/
          file_name: .env
          fail_on_empty: true

      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
          directory: front-end/
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose down && docker-compose up -d
